apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dagster-postgresql
  namespace: dagster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: dagster-postgresql
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: dagster/postgres
        property: admin-password
    - secretKey: postgresql-password
      remoteRef:
        key: dagster/postgres
        property: password
