apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dagster
  namespace: dagster
spec:
  interval: 1h
  url: https://dagster-io.github.io/helm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: dagster
spec:
  interval: 1h
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
