apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infrastructure
patches:
  - path: apps/whoami/deployment-patch.yaml
  - path: monitoring/grafana-release-patch.yaml
  - path: ingress/grafana-ingress-patch.yaml
