apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infrastructure
  - ../../infrastructure/monitoring
  - ingress/grafana-ingress.yaml
patches:
  - path: apps/whoami/deployment-patch.yaml
