---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCLOhHTge1dbKX/EeiAVaDNxRFK4hVm+pI5cm/F9g2bcD69xk1EAi4wIoLPjM8Vu/mexEpFwxyTpaq4MRIn4JlqGoBhm2VwGXjq7dK8hludCn5qGbvv9PMg3nSwrwaxHGpHuwQQZbuxfsVqIA5kqYR6IxncrZu9+AYeHBfJt+ZBo25Y2E+8Sf4J2jojyUoVkTgNsVxPHNIdlUPVAcWi6njUFxQjMgI8wPCsp+ewNXU2AmF5N+7QkbMhP2L2F+KJxaCE+qFcrFDH4D/LZhswhxuwVckLxbEkrFBBifGY5Qtp+/g6Gt/0iOtOs28jfdQcXMSNXOGkEsb1ymv095pAv1lCSVvQCPyNuvc4vUMn+k+6aQM0zeupeDC5Esh/782zuD3boYexJ+zBgqDHnczTlrnGwfOT0vsSFPOoIjkEFHt0K106WJH0ufMFH/HzSp/kPeeHJYjKvR958kKbKDklaKbkBN2VVfVKZuu+too/7cBUtTinsxgModbLWmguO0RUd8qNAYB9ldVf+4C9HXHIsFzDrhwMmPul7mFutoAK4u/CANFgD8Z6XpS8XUuxr62E64hQET3uIKp5ZOXCLTs1g0ntNMihLw5dD7lJgmAsBNioZhtWc/58woI3F5Llb9j1VYxXFsSn93lDuXaRgYY6QD+yx5ocsqR6V8MQp0mBGKtNZZXB9bwnlaz9mQljzfboh/oVh7y9NhgOhXM=
    admin-user: AgCQZGFssQ03tGrrdLysI3gx2lmxkEwSWEMRSnk8vxFS5mpKPF1o+ggD9+tl2xnFMC/cWFWxfr7fdTaTPZ7gPmblQRyg02wzO8MjvHKZKm68bISYyiHFibhyM7JfYfl7IZAPe2AP2DZvkcO0Xogf4Pr8jCEdKPeZFP8BmhJfnTu7opl/uyh70C8t45cBvOYHsb31DspS6KNVIR2YzHwn2t7FPqCsIwJdcFC4s3Udsx83u5tQo52f6rzaV/7kM+l9tXOQ0ZQRqh+lbzqnfVyFwl5VN7LDd3wR/igSqJnsElHTQpQsxIwzuBof+ENMVcdosXVMtPpTxY+oGnDSjyo6xYYtn5KNRGRWEDqT0x/wY4XikjkAGFs3RJrbIe8l4jmvA7cMiRuVTf/zurZcoBTpi38sOgqQ+i66OGd4nLYr1G2aEc/ERkEdkGGBzJUD3v27a0uGXn7747IPedZAGzpLHSe9yCeVPZcQyHa3iDuVYnOxk0YmUBlUnv0WxV/E0dXh6mzqa8aOU8kcHnc5do1RYIBKODmLXwNXlRJ9TL7AqmZ0OC/IIP2UgSzSt8TWgCdene4KaN+ESvVW6OFQ+RsRhqrOeb4bUPg1Olyijd53EALjcColEjTcDNOwv2OtWli77MEMspskokdVHfMk9FG3v7K9PYOS4k0+8cUlLgcjx5OY59TBNFzu1ZA1pvZ5opNAgNUtrqeODg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
