apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: secrets-infrastructure
spec:
  interval: 1h
  url: https://helm.releases.hashicorp.com
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: secrets-infrastructure
spec:
  interval: 1h
  url: https://charts.external-secrets.io
